export enum PluginType {
    None = "none",
    ApplicationSearchPlugin = "application-search-plugin",
    UeliCommandSearchPlugin = "ueli-command-search-plugin",
    ShortcutsSearchPlugin = "shortcuts-search-plugin",
    EverythingSearchPlugin = "everything-search-plugin",
    MdFindExecutionPlugin = "md-find-execution-plugin",
    TranslationPlugin = "translation-plugin",
    WebSearchPlugin = "websearch-plugin",
    FileBrowserPlugin = "filebrowser-plugin",
    OperatingSystemCommandsPlugin = "operating-system-commands-plugin",
    Calculator = "calculator",
    Url = "Url",
    Email = "Email",
    CurrencyConverter = "Currency Converter",
    Test = "Test",
}
