export enum PluginType {
    None = "none",
    ApplicationSearchPlugin = "application-search-plugin",
    UeliCommandSearchPlugin = "ueli-command-search-plugin",
    ShortcutsSearchPlugin = "shortcuts-search-plugin",
    EverythingSearchPlugin = "everything-search-plugin",
    MdFindExecutionPlugin = "md-find-execution-plugin",
    TranslationPlugin = "translation-plugin",
    WebSearchPlugin = "websearch-plugin",
    FileBrowserPlugin = "filebrowser-plugin",
    OperatingSystemCommandsPlugin = "operating-system-commands-plugin",
    OperatingSystemSettingsPlugin = "operating-system-settings-plugin",
    Calculator = "calculator-plugin",
    Url = "url-plugin",
    Email = "email-plugin",
    CurrencyConverter = "currency-converter-plugin",
    Workflow = "workflow-plugin",
    Commandline = "commandline-plugin",
    SimpleFolderSearch = "simple-folder-search-plugin",
    Uwp = "uwp",
    ColorConverter = "color-converter",
    BrowserBookmarks = "browser-bookmarks",
    Test = "test-plugin",
}
