export enum GlobalHotKeyKey {
    Plus = "Plus",
    Space = "Space",
    Tab = "Tab",
    Backspace = "Backspace",
    Delete = "Delete",
    Insert = "Insert",
    Return = "Return",
    Up = "Up",
    Down = "Down",
    Left = "Left",
    Right = "Right",
    Home = "Home",
    End = "End",
    PageUp = "PageUp",
    PageDown = "PageDown",
    Escape = "Escape",
}
