export enum IpcChannels {
    search = "search",
    searchResponse = "search-response",
    execute = "execute",
    mainWindowHasBeenHidden = "main-window-has-been-hidden",
    mainWindowHasBeenShown = "main-window-has-been-shown",
    userInputHasBeenResetAndMainWindowCanBeHidden = "user-input-has-been-reset-and-main-window-can-be-hidden",
    reloadApp = "reload-app",
    openSettingsWindow = "open-settings-window",
    configUpdated = "config-updated",
    indexRefreshSucceeded = "index-refresh-succeeded",
    indexRefreshFailed = "index-refresh-failed",
    appearanceOptionsUpdated = "user-styles-updated",
    ueliCommandExecuted = "ueli-command-executed",
}
