export enum VueEventChannels {
    enterPress = "enter-press",
    executionSucceeded = "execution-succeeded",
    handleExecution = "handle-execution",
    mainWindowHasBeenShown = "main-window-has-been-shown",
    userInputChange = "my-event",
    userInputHasBeenReset = "user-input-has-been-reset",
    selectNextItem = "select-next-item",
    selectPreviousItem = "select-previous-item",
    searchResultsUpdated = "search-results-updated",
    configUpdated = "config-updated",
    pushNotification = "push-notification",
    showSetting = "show-setting",
    loadingStarted = "loading-started",
    loadingCompleted = "loading-completed",
}
